// tree-sitter grammar for Mycelium — GENERATED by tools/grammar/generate.py. DO NOT EDIT.
//
// Status (RFC-0026 §3.4 follow-up; v2): STRUCTURAL grammar derived from the normative oracle
// docs/spec/grammar/mycelium.ebnf + the L1 lexer (crates/mycelium-l1/src/{lexer,token}.rs). The
// keyword sets below are lexer-derived and kept in lockstep by `just drift-check`; the structural
// productions are Empirical — verified by parsing the conformance accept corpus and lib/std/*.myc
// with zero ERROR nodes, not proven equivalent to the EBNF (which stays the accept/reject oracle).
// Two DOCUMENTED permissive deviations (Declared, G2): (1) reserved-not-active keywords parse as
// an explicit `reserved_keyword` atom (the L1 parser rejects them; a highlighting grammar renders
// them in snippets/docs); (2) repr-type brace arities are checker territory, not enforced here.
// Highlight captures are in queries/highlights.scm.

// GENERATED keyword sets (lexer-derived, G2 — the drift gate keeps these current).
const KW_KEYWORD = ['backbone', 'colony', 'consume', 'cyst', 'default', 'derive', 'else', 'fn', 'for', 'forage', 'fuse', 'graft', 'grow', 'hypha', 'if', 'impl', 'in', 'lambda', 'let', 'lower', 'match', 'matured', 'mesh', 'nodule', 'object', 'paradigm', 'phylum', 'policy', 'priv', 'pub', 'reclaim', 'spore', 'swap', 'thaw', 'then', 'tier', 'to', 'trait', 'type', 'use', 'via', 'wild', 'with', 'wrapping', 'xloc'];
const KW_TYPE = ['Binary', 'Bytes', 'Dense', 'Float', 'Seq', 'Sparse', 'Substrate', 'Ternary', 'VSA', 'bin', 'emb', 'hvec', 'tern'];
const KW_SCALAR = ['BF16', 'F16', 'F32', 'F64'];
const KW_STRENGTH = ['Declared', 'Empirical', 'Exact', 'Proven'];
// Reserved-not-active (DN-03 §4; EBNF header): lexed as keywords, consumed by no production.
const KW_RESERVED_INACTIVE = ['backbone', 'cyst', 'graft', 'grow', 'matured', 'mesh', 'priv', 'wrapping', 'xloc'];

// RFC-0025 §4.1 tiers (M-705/M-745), written loosest→tightest; every binary operator is
// left-associative, prefix operators bind tighter than every binary operator.
const PREC = {
  OR: 2, AND: 3, EQ: 4, CMP: 5, BOR: 6, XOR: 7, BAND: 8, SHIFT: 9, ADD: 10, MUL: 11,
  UNARY: 12, ASCRIPTION: 13, CALL: 14,
};

function sep1(rule, sep) {
  return seq(rule, repeat(seq(sep, rule)));
}

module.exports = grammar({
  name: 'mycelium',
  word: $ => $.identifier,
  extras: $ => [/\s/, $.comment],

  rules: {
    // program ::= phylum_header? nodule_block+ — flattened to a component list: the DN-57 §3
    // mandatory `;` terminator makes every component self-delimiting, so the flat form parses
    // the same programs (nodule_header opens a block; items follow until the next header).
    source_file: $ => seq(
      optional($.phylum_header),
      repeat(choice($.nodule_header, seq($._item, ';'))),
    ),

    // ── headers ────────────────────────────────────────────────────────────────────────────
    phylum_header: $ => seq('phylum', field('name', $._path)),
    // The `@std-sys` marker (M-661) is ONE atomic token (the `-` could not lex as `@` + ident).
    nodule_header: $ => seq('nodule', field('name', $._path), optional($.std_sys_marker), ';'),
    std_sys_marker: $ => token('@std-sys'),

    // ── items ──────────────────────────────────────────────────────────────────────────────
    _item: $ => choice(
      $.use_item, $.default_item, $.type_item, $.trait_item, $.impl_item,
      $.fn_item, $.object_item, $.lower_item, $.derive_item,
    ),

    // the glob tail `.*` lexes as ONE token, so `use a.b.*` never conflicts with a longer path.
    use_item: $ => seq('use', field('path', $._path), optional(token('.*'))),

    default_item: $ => seq('default', 'paradigm', $.paradigm),
    paradigm: $ => choice('Binary', 'Ternary', 'Dense', 'VSA'),

    type_item: $ => seq(
      optional('pub'), 'type', field('name', $.identifier), optional($.type_params),
      '=', sep1($.constructor, '|'),
    ),
    constructor: $ => seq(
      field('name', $.identifier),
      optional(seq('(', sep1($.type_ref, ','), ')')),
    ),

    trait_item: $ => seq(
      optional('pub'), 'trait', field('name', $.identifier), optional($.type_params),
      '{', repeat(seq($.fn_sig, ';')), '}',
    ),
    fn_sig: $ => seq(
      'fn', field('name', $.identifier), optional($.type_params), optional($.const_params),
      '(', optional($.params), ')', '=>', field('return_type', $.type_ref), optional($.effects),
    ),

    // impl: trait-instance `impl Trait[args]? for T { … }` / inherent `impl T { … }` (M-659/
    // M-664) — unified head (a trait head `Ident type_args?` is a named type_ref).
    impl_item: $ => seq(
      'impl', field('trait_or_type', $.type_ref),
      optional(seq('for', field('type', $.type_ref))),
      '{', repeat(seq($.fn_item, ';')), '}',
    ),

    fn_item: $ => seq(
      optional('pub'), optional($.tier_attribute), optional('thaw'),
      'fn', field('name', $.identifier), optional($.type_params), optional($.const_params),
      '(', optional($.params), ')', '=>', field('return_type', $.type_ref), optional($.effects),
      '=', field('body', $._expr),
    ),
    // `@tier(compiled|interpreted)` (DN-58 §C; M-667) — the mode names are plain identifiers in
    // the lexer (RFC-0004 surface spellings, validated by the checker, not the grammar).
    tier_attribute: $ => seq('@', 'tier', '(', field('mode', $.identifier), ')'),

    // object composition (DN-53 / M-811): one constructor clause, then via/impl/fn members.
    object_item: $ => seq(
      optional('pub'), 'object', field('name', $.identifier), optional($.type_params),
      '{', $.constructor, ';', repeat(seq($._object_member, ';')), '}',
    ),
    _object_member: $ => choice($.via_clause, $.impl_item, $.fn_item),
    via_clause: $ => seq('via', field('index', $.int_literal), ':', field('trait', $.identifier), optional($.type_args)),

    // user-extensible generative lowering (DN-54 / M-812).
    lower_item: $ => seq('lower', field('name', $.identifier), optional($.type_params), '=', field('body', $._expr)),
    derive_item: $ => seq('derive', field('name', $.identifier), 'for', field('type', $.type_ref)),

    params: $ => sep1($.param, ','),
    param: $ => seq(field('name', $.identifier), ':', field('type', $.type_ref)),

    // effect annotation `!{ … }` (RFC-0014 §3.4; M-660): names are plain identifiers.
    effects: $ => seq('!', '{', optional(sep1($.identifier, ',')), '}'),

    // ── types ──────────────────────────────────────────────────────────────────────────────
    // type_ref ::= base_type ('@' strength)? ('=>' type_ref)? — the guarantee tag as a
    // type-level index (LR-6), plus the FUNCTION TYPE arrow (RFC-0024 §3 / RFC-0037 D4:
    // right-associative `A => B => C`; `@` binds tighter than `=>` — parse.rs
    // parse_type_ref_guarded; NOTE: implemented in the L1 parser, not yet in mycelium.ebnf).
    type_ref: $ => prec.right(seq(
      $._base_type,
      optional(seq('@', field('strength', $.strength))),
      optional(seq('=>', field('return', $.type_ref))),
    )),
    strength: $ => choice(...KW_STRENGTH),
    scalar_type: $ => choice(...KW_SCALAR),

    _base_type: $ => choice($.repr_type, $.tuple_type, $.ambient_type, $.named_type),
    // Repr types + the RFC-0037 D2-b short aliases (M-915). Brace ARITIES are checker territory
    // (documented deviation #2): each takes a comma list of width/scalar/sparsity/type args.
    repr_type: $ => choice(
      seq(
        // `Sparse` is NOT a repr head — it appears only inside the `sparsity` spec (EBNF).
        field('paradigm', choice(
          'Binary', 'Ternary', 'Dense', 'VSA', 'bin', 'tern', 'emb', 'hvec',
          'Substrate', 'Seq',
        )),
        '{', sep1($._repr_arg, ','), '}',
      ),
      'Bytes',
      'Float',
    ),
    _repr_arg: $ => choice($.int_literal, $.scalar_type, $.sparsity, $.type_ref),
    sparsity: $ => choice('Dense', seq('Sparse', '{', choice($.int_literal, $.identifier), '}')),
    tuple_type: $ => seq('(', $.type_ref, ',', sep1($.type_ref, ','), ')'),
    // paradigm-less repr `{…}` (RFC-0012 §4.2): the ambient supplies the paradigm.
    ambient_type: $ => seq('{', sep1(choice($.int_literal, $.identifier, $.scalar_type, $.sparsity), ','), '}'),
    named_type: $ => prec.right(seq(field('name', $.identifier), optional($.type_args))),
    type_args: $ => seq('[', sep1($.type_ref, ','), ']'),
    type_params: $ => seq('[', sep1($.identifier, ','), ']'),
    const_params: $ => seq('{', sep1($.identifier, ','), '}'),

    // ── expressions ────────────────────────────────────────────────────────────────────────
    _expr: $ => choice(
      $.let_expr, $.if_expr, $.match_expr, $.for_expr, $.swap_expr, $.with_expr,
      $.wild_expr, $.spore_expr, $.consume_expr, $.colony_expr, $.fuse_expr,
      $.reclaim_expr, $.lambda_expr, $._op_expr,
    ),

    let_expr: $ => prec.right(seq(
      'let', field('name', $.identifier), optional(seq(':', field('type', $.type_ref))),
      '=', field('value', $._expr), 'in', field('body', $._expr),
    )),
    if_expr: $ => prec.right(seq(
      'if', field('condition', $._expr), 'then', field('consequence', $._expr),
      'else', field('alternative', $._expr),
    )),
    match_expr: $ => seq(
      'match', field('value', $._expr), '{', sep1($.match_arm, ','), optional(','), '}',
    ),
    // or-patterns `A | B => e` (M-823 / R20-Q3).
    match_arm: $ => seq(sep1($.pattern, '|'), '=>', field('value', $._expr)),
    pattern: $ => choice(
      '_',
      $._literal,
      $.tuple_pattern,
      seq(field('name', $.identifier), optional(seq('(', sep1($.pattern, ','), ')'))),
    ),
    tuple_pattern: $ => seq('(', $.pattern, ',', sep1($.pattern, ','), ')'),

    // for: bounded structural fold (RFC-0007 §4.8).
    for_expr: $ => seq(
      'for', field('binder', $.identifier), 'in', field('iterable', $._app_expr),
      ',', field('accumulator', $.identifier), '=', field('init', $._app_expr),
      '=>', field('body', $._expr),
    ),

    // swap: the never-silent representation change — target + policy ALWAYS lexical (S1/WF2).
    swap_expr: $ => seq(
      'swap', '(', field('value', $._expr), ',', 'to', ':', field('to', $.type_ref),
      ',', 'policy', ':', field('policy', $._path), ')',
    ),
    with_expr: $ => seq('with', 'paradigm', $.paradigm, '{', field('body', $._expr), '}'),
    wild_expr: $ => seq('wild', '{', field('body', $._expr), '}'),
    spore_expr: $ => seq('spore', '(', field('value', $._expr), ')'),
    consume_expr: $ => prec(PREC.UNARY, seq('consume', field('value', $._app_expr))),

    // colony/hypha (RFC-0008 §4.7; M-666) with optional `@forage(policy)` (DN-70 D1; M-906).
    colony_expr: $ => seq('colony', '{', sep1($.hypha, ','), optional(','), '}'),
    hypha: $ => seq(optional($.forage_attribute), 'hypha', field('value', $._app_expr)),
    forage_attribute: $ => seq('@', 'forage', '(', field('policy', $._expr), ')'),

    fuse_expr: $ => seq('fuse', '(', field('left', $._expr), ',', field('right', $._expr), ')'),
    reclaim_expr: $ => seq(
      'reclaim', '(', field('policy', $._expr), ')', '{', field('body', $._expr), '}',
    ),
    lambda_expr: $ => prec.right(seq(
      'lambda', '(', optional($.params), ')', '=>', field('body', $._expr),
    )),

    // operator layer (RFC-0025 / M-705 / M-745): `<=`/`>=` glyphs are RETIRED (RFC-0037 D1) —
    // `lte`/`gte` are ordinary word-form calls, so they appear as call_expr, not operators.
    _op_expr: $ => choice($.binary_expr, $.unary_expr, $._app_expr),
    binary_expr: $ => choice(
      prec.left(PREC.OR, seq(field('left', $._op_expr), field('operator', '||'), field('right', $._op_expr))),
      prec.left(PREC.AND, seq(field('left', $._op_expr), field('operator', '&&'), field('right', $._op_expr))),
      prec.left(PREC.EQ, seq(field('left', $._op_expr), field('operator', choice('==', '!=')), field('right', $._op_expr))),
      prec.left(PREC.CMP, seq(field('left', $._op_expr), field('operator', choice('<', '>')), field('right', $._op_expr))),
      prec.left(PREC.BOR, seq(field('left', $._op_expr), field('operator', '|'), field('right', $._op_expr))),
      prec.left(PREC.XOR, seq(field('left', $._op_expr), field('operator', '^'), field('right', $._op_expr))),
      prec.left(PREC.BAND, seq(field('left', $._op_expr), field('operator', '&'), field('right', $._op_expr))),
      prec.left(PREC.SHIFT, seq(field('left', $._op_expr), field('operator', choice('<<', '>>')), field('right', $._op_expr))),
      prec.left(PREC.ADD, seq(field('left', $._op_expr), field('operator', choice('+', '-')), field('right', $._op_expr))),
      prec.left(PREC.MUL, seq(field('left', $._op_expr), field('operator', choice('*', '/', '%')), field('right', $._op_expr))),
    ),
    unary_expr: $ => prec.right(PREC.UNARY, seq(field('operator', choice('-', '!')), field('operand', $._op_expr))),

    // app_expr ::= primary calls* (':' type_ref)? — ascription binds looser than a call,
    // tighter than every operator.
    _app_expr: $ => choice($.call_expr, $.ascription_expr, $._primary),
    call_expr: $ => prec.left(PREC.CALL, seq(
      field('function', $._app_expr), '(', optional(sep1($._expr, ',')), ')',
    )),
    ascription_expr: $ => prec.left(PREC.ASCRIPTION, seq(
      field('value', $._app_expr), ':', field('type', $.type_ref),
    )),

    _primary: $ => choice(
      $._literal, $.identifier, $.path, $.tuple_expr, $.paren_expr, $.reserved_keyword,
    ),
    tuple_expr: $ => seq('(', $._expr, ',', sep1($._expr, ','), ')'),
    paren_expr: $ => seq('(', $._expr, ')'),
    // a dotted path has >= 2 segments; `_path` admits the single-segment (bare-ident) form.
    _path: $ => choice($.identifier, $.path),
    path: $ => prec.left(seq($.identifier, repeat1(seq('.', $.identifier)))),

    // Documented permissive deviation #1: the reserved-not-active vocabulary parses as an
    // explicit atom (the L1 parser REJECTS these — conformance/reject/12; a highlighting
    // grammar renders them in snippets/docs rather than erroring).
    reserved_keyword: $ => choice(...KW_RESERVED_INACTIVE),

    // ── literals (lexer terminals; mycelium.ebnf §Terminals) ───────────────────────────────
    _literal: $ => choice(
      $.bin_literal, $.trit_literal, $.bytes_literal, $.string_literal,
      $.float_literal, $.int_literal, $.list_literal,
    ),
    bin_literal: $ => token(/0b[01_]+/),
    trit_literal: $ => token(/0t[+0-]+/),
    bytes_literal: $ => token(/0x[0-9A-Fa-f_]+/),
    // FloatLit (ADR-040; M-897): digits `.` digits exponent? | digits exponent. `1.` stays
    // Int + `.` (the path glyph) — no trailing-dot float, no leading-dot `.5`.
    float_literal: $ => token(choice(
      /[0-9]+\.[0-9]+([eE][+-]?[0-9]+)?/,
      /[0-9]+[eE][+-]?[0-9]+/,
    )),
    int_literal: $ => token(/[0-9]+/),
    // StrLit (M-910/M-911): minimal escape set; no raw newline/CR inside the literal.
    string_literal: $ => seq(
      '"',
      repeat(choice($.escape_sequence, token.immediate(prec(1, /[^"\\\n\r]+/)))),
      '"',
    ),
    escape_sequence: $ => token.immediate(/\\[nt\\"0r]/),
    list_literal: $ => seq('[', optional(sep1($._expr, ',')), ']'),

    comment: $ => token(seq('//', /[^\n]*/)),
    identifier: $ => /[A-Za-z_][A-Za-z0-9_]*/,
  },
});
