#!/usr/bin/env node
// Copies the canonical, generated TextMate grammar from tools/grammar/ into this
// extension's syntaxes/ directory. The canonical file is generated by
// tools/grammar/generate.py from the L1 lexer keyword table (drift-gated via
// `just drift-check`) — never hand-edit either copy.
//
// Usage: node scripts/sync-grammar.js   (invoked via `npm run sync-grammar`)

'use strict';

const fs = require('fs');
const path = require('path');

const SRC = path.resolve(__dirname, '..', '..', '..', 'tools', 'grammar', 'mycelium.tmLanguage.json');
const DEST_DIR = path.resolve(__dirname, '..', 'syntaxes');
const DEST = path.join(DEST_DIR, 'mycelium.tmLanguage.json');

function main() {
  if (!fs.existsSync(SRC)) {
    console.error(`sync-grammar: source not found at ${SRC}`);
    console.error('sync-grammar: expected the canonical generated grammar under tools/grammar/');
    process.exit(1);
  }

  if (!fs.existsSync(DEST_DIR)) {
    fs.mkdirSync(DEST_DIR, { recursive: true });
  }

  const contents = fs.readFileSync(SRC, 'utf8');

  // Validate it parses as JSON before writing — never propagate a corrupt copy.
  try {
    JSON.parse(contents);
  } catch (err) {
    console.error(`sync-grammar: source at ${SRC} is not valid JSON: ${err.message}`);
    process.exit(1);
  }

  fs.writeFileSync(DEST, contents, 'utf8');
  console.log(`sync-grammar: copied ${SRC} -> ${DEST}`);
}

main();
