; tree-sitter highlight queries for Mycelium — GENERATED by tools/grammar/generate.py.
; Status: SCOPE/CAPTURE NAMES ARE PROVISIONAL — RFC-0026 §3.2 OPEN (Draft). Not final (VR-5/G2).

["backbone" "colony" "cyst" "default" "else" "fn" "for" "forage" "fuse" "graft" "hypha" "if" "impl" "in" "let" "match" "matured" "mesh" "nodule" "paradigm" "phylum" "policy" "pub" "reclaim" "spore" "swap" "thaw" "then" "tier" "to" "trait" "type" "use" "wild" "with" "xloc"] @TODO.rfc-0026.keyword
["Binary" "Dense" "Sparse" "Substrate" "Ternary" "VSA"] @TODO.rfc-0026.type
["BF16" "F16" "F32" "F64"] @TODO.rfc-0026.scalar
["Declared" "Empirical" "Exact" "Proven"] @TODO.rfc-0026.strength
