#!/usr/bin/env python3
"""Generate a top-level rustdoc/index.html listing every crate's own rustdoc index.

`cargo doc --workspace --no-deps` emits one `<crate>/index.html` per crate but no top-level
index (a known rustdoc gap) — this writes a small, honest landing page over exactly the crate
directories that were actually generated (never a hardcoded, driftable list). Used by
docs/Containerfile (the docs container build stage); no heavy dep, stdlib only.

Usage: gen-rustdoc-index.py <rustdoc_out_dir>
"""

import html
import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: gen-rustdoc-index.py <rustdoc_out_dir>", file=sys.stderr)
        return 64
    out_dir = Path(sys.argv[1])
    if not out_dir.is_dir():
        print(f"gen-rustdoc-index.py: no such directory: {out_dir}", file=sys.stderr)
        return 66

    crates = sorted(
        p.name
        for p in out_dir.iterdir()
        if p.is_dir() and (p / "index.html").is_file()
    )

    items = "\n".join(
        f'  <li><a href="{html.escape(c)}/index.html"><code>{html.escape(c)}</code></a></li>'
        for c in crates
    )
    page = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Mycelium &mdash; Rustdoc</title>
<style>
:root{{--fg:#1a1a2e;--bg:#fdfdfd;--accent:#3a5;--dim:#667}}
body{{margin:0;font:16px/1.6 system-ui,-apple-system,Segoe UI,Roboto,sans-serif;color:var(--fg);background:var(--bg)}}
header,main,footer{{max-width:54rem;margin:0 auto;padding:1rem 1.25rem}}
header{{border-bottom:2px solid var(--accent)}}
a{{color:var(--accent)}}
ul{{padding-left:1.5rem;columns:2}}
li{{margin:.3rem 0}}
code{{font:0.9em ui-monospace,SFMono-Regular,Menlo,monospace}}
footer{{color:var(--dim);font-size:.85rem;border-top:1px solid #ddd;margin-top:2rem}}
</style>
</head>
<body>
<header><h1>Mycelium &mdash; Rustdoc</h1>
<p><a href="../index.html">&larr; Back to docs landing</a></p></header>
<main>
<ul>
{items}
</ul>
</main>
<footer>Generated by <code>cargo doc --workspace --no-deps</code> + this listing script
(rustdoc emits no top-level index by design). {len(crates)} crates.</footer>
</body>
</html>
"""
    (out_dir / "index.html").write_text(page)
    print(f"gen-rustdoc-index.py: wrote {out_dir / 'index.html'} ({len(crates)} crates)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
